# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37fec2d8a2cec2cec402d7e4221eeae738efb28870368d348ecbaf9e27a337556525bb9b1b4142e45c4ab724a973dba71b4671dab94150d1615f58b86d7c415

test:
  secret_key_base: 4ff5a47138f2089aa337d247c5cec3a56cf1d0ce497c2230fa913f7bf0878b3edb4e3d1de631c4ea9aeec57c2fbce8116307b01eddaf4d3978e24a5b6d4e2c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
